### ISSUE TITLE
[BUG]: Different processes between Illumina and Nanopore platforms

### ISSUE THREAD

**Issue by kdl480** [peterk87/nf-flu#15]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Bug/Issue

I'm working on validating this pipeline on samples sequenced on both Illumina and Nanopore platforms. I noticed the processes are different between the two, with more results being provided with the Nanopore platform (e.g. coverage_plots, mapping, mosdepth, MultiQC, read_count, reference_sequences, variants). Is there any way to have these processes included with the Illumina workflow as well?

### Nextflow command-line

```shell
nextflow run CFIA-NCFAD/nf-flu --input samplesheet.csv --platform nanopore/illumina -profile conda
```

### Error Message

```shell
Missing these result directories with the Illumina work flow:
coverage_plots, mapping, mosdepth, MultiQC, read_count, reference_sequences, variants
```

### Workflow Version

v3.1.0

### Nextflow Executor

local

### Nextflow Version

22.04.3

### Java Version

openjdk 11.0.9.1-internal 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1-internal+0-adhoc..src)
OpenJDK 64-Bit Server VM (build 11.0.9.1-internal+0-adhoc..src, mixed mode)

### Hardware

Desktop

### Operating System (OS)

Ubuntu 20.04

### Conda/Container Engine

Conda

**Comment by peterk87** [comment]
Hi @kdl480 it's on the roadmap. We've transitioned to doing the majority of our influenza sequencing on Nanopore so getting the Nanopore workflow up and running with the features we needed was a top priority. The Illumina subworkflow will have the same steps added soon.

**Comment by kdl480** [comment]
Okay, sounds great. Thank you so much for these :)

**Comment by stefkary** [comment]
@peterk87 I was wondering if there are any updates on full Illumina implementation of the pipeline? We would be really interested to have the first table in the Multi-QC to be able to compare runs on Illumina and Nanopore more easily.

**Comment by peterk87** [comment]
Illumina workflow should be in line with the Nanopore workflow since [CFIA-NCFAD/nf-flu release 3.5.0](https://github.com/CFIA-NCFAD/nf-flu/releases/tag/3.5.0) with additional read mapping, variant calling, consensus sequence and MultiQC report generation after IRMA assembly and BLAST of IRMA consensus sequences against the Orthomyxoviridae sequence DB from NCBI.
