### ISSUE TITLE
[BUG]: failed profile test

### ISSUE THREAD

**Issue by egenomics** [peterk87/nf-flu#18]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Bug/Issue

Test profile is not working

### Nextflow command-line

```shell
nextflow run CFIA-NCFAD/nf-flu -profile test,docker
```

### Error Message

```shell
N E X T F L O W  ~  version 23.04.3
Pulling CFIA-NCFAD/nf-flu ...
 downloaded from https://github.com/CFIA-NCFAD/nf-flu.git
Unknown configuration profile: 'test'
```

### Workflow Version

3.3.5

### Nextflow Executor

local

### Nextflow Version

23.04.3.5875

### Java Version

11.0.20.1

### Hardware

Desktop

### Operating System (OS)

Ubuntu 22.04

### Conda/Container Engine

Docker

**Comment by peterk87** [comment]
Hi @egenomics 

I've created an issue in the main repo:

https://github.com/CFIA-NCFAD/nf-flu/issues/52

Feel free to comment there with more info.

Thanks,
Peter
