### ISSUE TITLE
[BUG]: Integrated Illumina test fails on VADR

### ISSUE THREAD

**Issue by marchoeppner** [peterk87/nf-flu#21]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Bug/Issue

Using the command line below on the most recent version of the code from master branch (as of writing) fails on the VADR process with:

```
ERROR, at least one sequence name exceeds the maximum GenBank allowed length of 50:
  451130_32_ferret-332_day_4-1-FLU-generic-ngsservice-processed_1
  To bypass this restriction, rerun with the --noseqnamemax option enabled.
``` 

Not sure if VADR was recently updated, but this is probably fixable by simply passing the suggested command line option via the module.config. 

### Nextflow command-line

```shell
nextflow run peterk87/nf-flu -profile singularity,test_illumina
```

### Error Message

```shell
ERROR, at least one sequence name exceeds the maximum GenBank allowed length of 50:
  451130_32_ferret-332_day_4-1-FLU-generic-ngsservice-processed_1
  To bypass this restriction, rerun with the --noseqnamemax option enabled.
```
```


### Workflow Version

revision 766e586

### Nextflow Executor

local

### Nextflow Version

24.04.4

### Java Version

21.0.4

### Hardware

Desktop

### Operating System (OS)

AlmaLinux 9.4

### Conda/Container Engine

Singularity

### Additional context

_No response_

**Comment by peterk87** [comment]
Hi @marchoeppner the issue should be resolved in [CFIA-NCFAD/nf-flu release 3.5.1](https://github.com/CFIA-NCFAD/nf-flu/releases/tag/3.5.1)
